### ISSUE TITLE
Openrefine can't connect to the openrefine-wikibase

### ISSUE THREAD

**Issue by belletractopelle** [wetneb/openrefine-wikibase#106]
Hello,
I installed an openrefine-wikibase container without trouble (by the way, [this](https://github.com/belletractopelle/openrefine-wikibase/blob/master/config.py) is my config file).

Using openrefine, I can reconcile data with wikidata but when I try with my own wikibase instance it fails. I write the service's URL (which is http://localhost:8000/en/api), the 'working...' message appears but nothing happens then (and the spinner progress bar is still spinning).

In my wikibase-openrefine terminal, i get this : 
```
reconcile_1  | Traceback (most recent call last):
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
reconcile_1  |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
reconcile_1  |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
reconcile_1  |     raise exceptions[0]
reconcile_1  |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
reconcile_1  |     await self.sock_connect(sock, address)
reconcile_1  |   File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
reconcile_1  |     return await fut
reconcile_1  |   File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
reconcile_1  |     raise OSError(err, f'Connect call failed {address}')
reconcile_1  | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8181)
reconcile_1  | 
reconcile_1  | The above exception was the direct cause of the following exception:
reconcile_1  | 
reconcile_1  | Traceback (most recent call last):
reconcile_1  |   File "app.py", line 58, in wrapped
reconcile_1  |     result = await view(args, *posargs, **kwargs)
reconcile_1  |   File "app.py", line 88, in api_custom_lang
reconcile_1  |     return await api(args)
reconcile_1  |   File "app.py", line 111, in api
reconcile_1  |     default_language=lang)
reconcile_1  |   File "/openrefine-wikibase/wdreconcile/engine.py", line 175, in process_queries
reconcile_1  |     for query_id, query in queries_with_ids
reconcile_1  |   File "/openrefine-wikibase/wdreconcile/engine.py", line 127, in fetch_candidate_ids
reconcile_1  |     num_results_before_filter, default_language)
reconcile_1  |   File "/openrefine-wikibase/wdreconcile/engine.py", line 43, in wikibase_string_search
reconcile_1  |     self._wbsearchentities(query_string, num_results, default_language))
reconcile_1  |   File "/openrefine-wikibase/wdreconcile/engine.py", line 56, in _srsearch
reconcile_1  |     headers=config.headers) as r:
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
reconcile_1  |     self._resp = await self._coro
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
reconcile_1  |     req, traces=traces, timeout=real_timeout
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
reconcile_1  |     proto = await self._create_connection(req, traces, timeout)
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
reconcile_1  |     _, proto = await self._create_direct_connection(req, traces, timeout)
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
reconcile_1  |     raise last_exc
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
reconcile_1  |     client_error=client_error,
reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
reconcile_1  |     raise client_error(req.connection_key, exc) from exc
reconcile_1  | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8181 ssl:default [Connect call failed ('127.0.0.1', 8181)]
reconcile_1  | [2021-03-31 13:15:37,576] 192.168.0.23:41692 POST /en/api 1.1 403 368 11817
```
What's wrong with it ? Did I do something wrong ?

**Comment by wetneb** [comment]
It looks like the reconciliation service is trying to talk to your wikibase instance at `localhost:8181` and fails to do so. Can you access your Wikibase instance properly at this address? If so this is probably an issue with the way you expose ports between your various Docker containers, I suspect?

**Comment by wetneb** [comment]
deployment issue, not an issue with our codebase
