### ISSUE TITLE
Exception when trying to add OpenRefine date (not string) values with too high precision

### ISSUE THREAD

**Issue by davidabian** [wetneb/openrefine-wikibase#54]
I got...
```
org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] Out of range, must be no higher than 11
  at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:62)
  at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:422)
  at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:362)
  at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:720)
  at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:298)
  at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.createItemDocument(WikibaseDataEditor.java:247)
  at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:140)
  at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:211)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by davidabian** [comment]
Although the intended precision was days, I suspect the underlying precision was higher than days (>11, with 0s for hours/minutes/seconds), which totally explains the exception, the highest precision allowed by Wikibase is days. If that's the problem, precisions greater than days (i.e., time of day) should probably be cut and a warning may be displayed. Sadly this happened some days ago, I only copied the backtrace and don't have more details now.

**Comment by wetneb** [comment]
Transferred to https://github.com/OpenRefine/OpenRefine/issues/1944.
