### ISSUE TITLE
docker-compose issues and blank page

### ISSUE THREAD

**Issue by StylesTrip** [wetneb/openrefine-wikibase#86]
Hello,

Following along with the README to start this project up via `docker-compose` and ran into a couple issues.

First issue, after copying the `config_docker.py` to `config.py` and running `docker-compose up -d` got me this error in the openrefine-wikibase_reconcile_1 container:
```
Error starting up:
openrefine-wikibase (master) $ docker logs openrefine-wikibase_reconcile_1
Running on http://127.0.0.1:8000 (CTRL + C to quit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/quart/asgi.py", line 206, in __call__
    await self.app.startup()
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 2099, in startup
    await func()
  File "app.py", line 22, in setup
    app.redis_client = await aioredis.create_redis_pool(redis_uri)
  File "/usr/local/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 198, in create_redis_pool
    loop=loop)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 113, in create_connection
    timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/site-packages/aioredis/stream.py", line 24, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 968, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 333, in <module>
    app.run(debug=True, port=8000)
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1636, in run
    loop.run_until_complete(task)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "/usr/local/lib/python3.7/site-packages/hypercorn/asyncio/run.py", line 66, in worker_serve
    raise exception
  File "/usr/local/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.7/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
    await app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 2069, in __call__
    await self.asgi_app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 2092, in asgi_app
    await asgi_handler(receive, send)
  File "/usr/local/lib/python3.7/site-packages/quart/asgi.py", line 208, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "/usr/local/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 77, in asgi_send
    raise LifespanFailure("startup", message["message"])
hypercorn.utils.LifespanFailure: Lifespan failure in startup. 'Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Address not available'
```

I was able to get around this error by modifying the config.py redis_uri to `redis://redis:6739:6739` and also modifying the `docker-compose.yml` file from:
```
expose:
 - "6739"
```
to:
```
    ports:
      - "6379:6379"
```

With all of that done, both containers were up and running but going out to http://localhost:8000 got me an empty page saying "localhost did not send any data".

Something I did wrong or missed along the way in the README?

**Comment by wetneb** [comment]
Whoops, this might be linked to the changes I brought in recently, I probably broke the docker config with that. I will investigate.

**Comment by StylesTrip** [comment]
As a side note:
In the README the instructions say to copy `config-docker.py` to `config.py` but in the docker-compose, it does:
`source: ./config_docker.py`

Does that need to change to `source: ./config.py`?

**Comment by wetneb** [comment]
This should be fixed by c80c9fca87148db585a0f51b1d6660ed33610b05, but I did not need to change the `expose` to `ports` as you mentioned above. I am far from a Docker expert though, so perhaps your syntax is better?

**Comment by thadguidry** [comment]
`EXPOSE` is used in **Dockerfile**'s 
`ports:` is used in **docker-compose** files and is analogous.

Also options specified in a Dockerfile, like `EXPOSE` are respected by default in a service definition.
https://docs.docker.com/compose/compose-file/#service-configuration-reference

**Comment by StylesTrip** [comment]
[c80c9fc](https://github.com/wetneb/openrefine-wikibase/commit/c80c9fca87148db585a0f51b1d6660ed33610b05) did fix the issues I was having. Thank you!

And based on this StackOverflow [question](https://stackoverflow.com/questions/40801772/what-is-the-difference-between-docker-compose-ports-vs-expose), using `EXPOSE` for docker-compose.yml is the right way to go. `ports` would be for allowing me to reach it via localhost:<port>

**Comment by wetneb** [comment]
@StylesTrip thanks, feel free to make a PR for that and the config filename :)

**Comment by thadguidry** [comment]
@StylesTrip yes, `expose:` allows exposing the ports for linked services.  https://docs.docker.com/compose/compose-file/#expose
Depends on what you want to do.  `ports:` allows you control on the mapping as explained in detail here: https://docs.docker.com/compose/compose-file/#ports

**Comment by StylesTrip** [comment]
> @StylesTrip thanks, feel free to make a PR for that and the config filename :)

Does not appear that I have permissions to push to a branch to then create a PR off of. Did I mess something up or is there a different way to do it?

**Comment by wetneb** [comment]
@StylesTrip the way it normally works is that you first create a fork of the project, push your changes to a branch in your fork and then create the PR from there.
